In [1]:
from pathlib import Path

import pandas as pd

In [2]:
csv_dir = Path("../extracted_features/hg38_1mb_filtered_bins")
files = sorted(csv_dir.glob("*.csv"))

bin_ids = [f.name.split(".")[0] for f in files]
print("The number of samples processed for bin features is:", len(bin_ids))

The number of samples processed for bin features is: 528

In [3]:
summaries = []

for f in files:
    try:
        df_head = pd.read_csv(f, nrows=0)
        summaries.append(
            {
                "file": f.name,
                "n_cols": len(df_head.columns),
                "columns": tuple(df_head.columns),
            }
        )
    except Exception as e:
        summaries.append({"file": f.name, "error": str(e)})

summary_df = pd.DataFrame(summaries)
summary_df.head()

,file,n_cols,columns
0,EE87786.hg38.frag.tsv_BIN.csv,270,"(chrom, start, end, absolute_fragment_counts, ..."
1,EE87787.hg38.frag.tsv_BIN.csv,270,"(chrom, start, end, absolute_fragment_counts, ..."
2,EE87788.hg38.frag.tsv_BIN.csv,270,"(chrom, start, end, absolute_fragment_counts, ..."
3,EE87789.hg38.frag.tsv_BIN.csv,270,"(chrom, start, end, absolute_fragment_counts, ..."
4,EE87790.hg38.frag.tsv_BIN.csv,270,"(chrom, start, end, absolute_fragment_counts, ..."

In [4]:
# Check that all files have the same columns
print(summary_df["n_cols"].value_counts())
print(summary_df["columns"].value_counts())

n_cols
270    528
Name: count, dtype: int64
columns
(chrom, start, end, absolute_fragment_counts, relative_fragment_counts, absolute_short_fragments, absolute_long_fragments, mean_coverage, mean_coverage_short, mean_coverage_long, coverage_spread, fslr, fslr_coverage, rcov, griffin_diff, mwh, gc_content, mean_fragment_gc_content, mean_fragment_gc_content_short, mean_fragment_gc_content_long, mds, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, ...)    528
Name: count, dtype: int64

In [5]:
def count_rows(file, chunksize=100_000):
    total = 0
    for chunk in pd.read_csv(file, chunksize=chunksize):
        total += len(chunk)
    return total


row_counts = []

for f in files:
    try:
        row_counts.append({"file": f.name, "n_rows": count_rows(f)})
    except Exception as e:
        row_counts.append({"file": f.name, "error": str(e)})

rows_df = pd.DataFrame(row_counts)
rows_df.head()

                            file  n_rows
0  EE87786.hg38.frag.tsv_BIN.csv    2154
1  EE87787.hg38.frag.tsv_BIN.csv    2154
2  EE87788.hg38.frag.tsv_BIN.csv    2154
3  EE87789.hg38.frag.tsv_BIN.csv    2154
4  EE87790.hg38.frag.tsv_BIN.csv    2154

In [6]:
rows_df["n_rows"].describe()
rows_df["n_rows"].value_counts()

n_rows
2154    528
Name: count, dtype: int64

In [7]:
# Compare bin_samples to cris_bam.txt - to check all samples were processed

with open("../accessory_files/cris_bam.txt") as f:
    cris_bam_ids = [line.replace("cris/", "").split(".")[0] for line in f.readlines()]

# print(cris_bam_ids)
missing = list(set(cris_bam_ids) - set(bin_ids))
print("Number of missing samples:", len(missing))
print("Missing samples are:", missing)

Number of missing samples: 0
Missing samples are: []